/**
 * Generates public/sitemap.xml and public/robots.txt from buildPublicUrlInventory().
 * Run: npm run seo:generate
 */
import fs from "fs";
import path from "path";
import {
  buildPublicUrlInventory,
  CANONICAL_HOST,
} from "../src/lib/seo/publicUrlInventory";
import {
  buildPathLastModMap,
  lastModForPath,
} from "../src/lib/seo/sitemap-lastmod";

const PUBLIC_DIR = path.join(process.cwd(), "public");

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

function changefreqFor(pathname: string): string {
  if (pathname === "/") return "weekly";
  if (pathname.startsWith("/insights")) return "weekly";
  if (pathname.startsWith("/services")) return "monthly";
  if (pathname.startsWith("/case-types")) return "monthly";
  if (
    pathname === "/privacy-policy" ||
    pathname === "/terms" ||
    pathname === "/cookie-policy"
  ) {
    return "yearly";
  }
  return "monthly";
}

function priorityFor(pathname: string): string {
  if (pathname === "/") return "1.0";
  if (pathname === "/services/commercial-dispute-expert-witness") return "0.9";
  if (pathname === "/services" || pathname === "/case-types") return "0.85";
  if (pathname.startsWith("/services/")) return "0.8";
  if (pathname.startsWith("/case-types/")) return "0.75";
  if (pathname.startsWith("/insights")) return "0.7";
  if (
    pathname === "/privacy-policy" ||
    pathname === "/terms" ||
    pathname === "/cookie-policy"
  ) {
    return "0.3";
  }
  if (pathname === "/contact" || pathname === "/how-to-instruct") return "0.8";
  return "0.65";
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderSitemap(
  urls: string[],
  defaultLastmod: string,
  pathLastMod: Record<string, string>,
): string {
  const entries = urls
    .map((loc) => {
      const pathname = new URL(loc).pathname;
      const lastmod = lastModForPath(pathname, pathLastMod, defaultLastmod);
      return `  <url>
    <loc>${escapeXml(loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreqFor(pathname)}</changefreq>
    <priority>${priorityFor(pathname)}</priority>
  </url>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function renderRobots(host: string): string {
  return `# Generated by scripts/generate-seo.ts — do not edit by hand.
User-agent: *
Allow: /

Disallow: /api/
Disallow: /admin/
Disallow: /private/
Disallow: /.netlify/

Sitemap: ${host}/sitemap.xml
`;
}

function main(): void {
  const inventory = buildPublicUrlInventory(CANONICAL_HOST);
  const lastmod = todayUtc();
  const pathLastMod = buildPathLastModMap(lastmod);

  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  }

  const sitemapPath = path.join(PUBLIC_DIR, "sitemap.xml");
  const robotsPath = path.join(PUBLIC_DIR, "robots.txt");

  fs.writeFileSync(
    sitemapPath,
    renderSitemap(inventory.allUrls, lastmod, pathLastMod),
    "utf8",
  );
  fs.writeFileSync(robotsPath, renderRobots(inventory.canonicalHost), "utf8");

  const insightCount = inventory.allPaths.filter((p) => p.startsWith("/insights/")).length;
  console.log(`Wrote ${sitemapPath} (${inventory.allUrls.length} URLs, lastmod=${lastmod})`);
  console.log(`Wrote ${robotsPath}`);
  console.log(`  Insights in sitemap: ${insightCount}`);

  if (insightCount === 0) {
    console.warn(
      "Warning: No /insights/* URLs in sitemap. Add MDX files under content/insights/ if posts are missing.",
    );
  }
}

main();
